// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgUGrvJfcGJ_TUf5GRy2ka7CuXTNLeMXM',
    appId: '1:16689954534:web:dbd7e4069ae89ca324c527',
    messagingSenderId: '16689954534',
    projectId: 'electricians-912ad',
    authDomain: 'electricians-912ad.firebaseapp.com',
    storageBucket: 'electricians-912ad.firebasestorage.app',
    measurementId: 'G-D552RJDPLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAulkUkZuVhTg3QYSv_R984ZSEQtOpZ-0',
    appId: '1:16689954534:android:639c1317d144806724c527',
    messagingSenderId: '16689954534',
    projectId: 'electricians-912ad',
    storageBucket: 'electricians-912ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxJcQ0eZfBbs7BWaAo9WmGhIohBMWrkQ',
    appId: '1:16689954534:ios:81de76ae7e26b78524c527',
    messagingSenderId: '16689954534',
    projectId: 'electricians-912ad',
    storageBucket: 'electricians-912ad.firebasestorage.app',
    iosBundleId: 'com.example.electriciansapp',
  );
}
